[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    # Fail if the pickled model is loaded with a different scikit-learn version than it was trained with.
    error::sklearn.exceptions.InconsistentVersionWarning
