'use client'
import { useState } from 'react'
import { FileText, Download } from 'lucide-react'

interface Patient {
  id: string
  name: string
  age: number
  unit: string
}

interface Props {
  patients: Patient[]
  results: Record<string, { risk_score: number; risk_level: string; top_factors: {feature: string; impact: number}[] }>
}

export default function ShiftReport({ patients, results }: Props) {
  const [generated, setGenerated] = useState(false)
  const now = new Date()
  const shiftTime = now.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })
  const shiftDate = now.toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })

  const highRisk = patients.filter(p => results[p.id]?.risk_level === 'HIGH')
  const medRisk = patients.filter(p => results[p.id]?.risk_level === 'MEDIUM')
  const lowRisk = patients.filter(p => results[p.id]?.risk_level === 'LOW')
  const unassessed = patients.filter(p => !results[p.id])

  const handleDownload = () => {
    let text = `BIOSIGNAL ICU SHIFT HANDOVER REPORT\n`
    text += `Date: ${shiftDate} | Time: ${shiftTime}\n`
    text += `Generated by BioSignal ML Early Warning System\n\n`
    text += `=== PATIENT SUMMARY ===\n`
    text += `Total Patients: ${patients.length}\n`
    text += `HIGH RISK: ${highRisk.length} | MEDIUM: ${medRisk.length} | LOW: ${lowRisk.length}\n\n`

    if (highRisk.length > 0) {
      text += `=== HIGH RISK PATIENTS (Immediate Attention) ===\n`
      highRisk.forEach(p => {
        const r = results[p.id]
        text += `• ${p.name} (${p.age}y, ${p.unit}) — Risk: ${Math.round(r.risk_score * 100)}%\n`
        text += `  Top factors: ${r.top_factors.slice(0,2).map(f => f.feature).join(', ')}\n`
      })
      text += '\n'
    }

    text += `=== ALL PATIENTS ===\n`
    patients.forEach(p => {
      const r = results[p.id]
      text += `${p.name} | ${p.unit} | ${r ? Math.round(r.risk_score * 100) + '% ' + r.risk_level : 'NOT ASSESSED'}\n`
    })

    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = `biosignal-shift-report-${shiftDate}.txt`
    a.click(); URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-4">
      <div className="bg-gray-900 border border-gray-700 rounded-xl p-4">
        <div className="flex justify-between items-center">
          <div>
            <p className="text-white font-bold text-lg">ICU Shift Handover Report</p>
            <p className="text-xs text-gray-400">{shiftDate} • {shiftTime} • BioSignal ML System</p>
          </div>
          <button onClick={handleDownload}
            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold px-4 py-2 rounded-lg transition-all">
            <Download className="w-4 h-4" /> Download Report
          </button>
        </div>
      </div>

      <div className="grid grid-cols-4 gap-3">
        {[
          { label: 'Total Patients', count: patients.length, color: 'text-white', bg: 'bg-gray-800 border-gray-700' },
          { label: 'HIGH RISK', count: highRisk.length, color: 'text-red-400', bg: 'bg-red-950/50 border-red-800' },
          { label: 'MEDIUM RISK', count: medRisk.length, color: 'text-yellow-400', bg: 'bg-yellow-950/50 border-yellow-800' },
          { label: 'LOW RISK', count: lowRisk.length, color: 'text-green-400', bg: 'bg-green-950/50 border-green-800' },
        ].map((s, i) => (
          <div key={i} className={`border rounded-lg p-3 text-center ${s.bg}`}>
            <p className="text-xs text-gray-400">{s.label}</p>
            <p className={`text-3xl font-bold mt-1 ${s.color}`}>{s.count}</p>
          </div>
        ))}
      </div>

      {highRisk.length > 0 && (
        <div className="bg-red-950/30 border border-red-800 rounded-xl p-4">
          <p className="text-red-400 font-bold text-sm mb-3">🚨 HIGH RISK — Immediate Attention Required</p>
          <div className="space-y-2">
            {highRisk.map(p => {
              const r = results[p.id]
              return (
                <div key={p.id} className="bg-red-950/50 rounded-lg p-3">
                  <div className="flex justify-between">
                    <div>
                      <p className="text-white font-semibold text-sm">{p.name}</p>
                      <p className="text-xs text-gray-400">{p.age}y • {p.unit}</p>
                      <p className="text-xs text-red-300 mt-1">
                        Key factors: {r.top_factors.slice(0,2).map(f => f.feature.replace(/_/g,' ')).join(', ')}
                      </p>
                    </div>
                    <p className="text-red-300 font-black text-2xl">{Math.round(r.risk_score * 100)}%</p>
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      )}

      <div className="space-y-2">
        <p className="text-xs text-gray-500 uppercase tracking-wider">All Patients Status</p>
        {patients.map(p => {
          const r = results[p.id]
          return (
            <div key={p.id} className="flex items-center justify-between bg-gray-900 rounded-lg px-4 py-2.5">
              <div>
                <p className="text-sm text-white font-medium">{p.name}</p>
                <p className="text-xs text-gray-500">{p.age}y • {p.unit}</p>
              </div>
              {r ? (
                <span className={`text-xs font-bold px-3 py-1 rounded-full ${r.risk_level === 'HIGH' ? 'bg-red-900 text-red-300' : r.risk_level === 'MEDIUM' ? 'bg-yellow-900 text-yellow-300' : 'bg-green-900 text-green-300'}`}>
                  {Math.round(r.risk_score * 100)}% {r.risk_level}
                </span>
              ) : (
                <span className="text-xs text-gray-600 px-3 py-1 rounded-full bg-gray-800">Not Assessed</span>
              )}
            </div>
          )
        })}
      </div>

      {unassessed.length > 0 && (
        <p className="text-xs text-yellow-600 text-center">
          ⚠️ {unassessed.length} patient(s) not yet assessed — go to ML Dashboard and run predictions
        </p>
      )}
    </div>
  )
}
