'use client'
import { useState } from 'react'
import { Download } from 'lucide-react'

interface Patient { id:string;name:string;age:number;unit:string }
interface Props { patients:Patient[];results:Record<string,{risk_score:number;risk_level:string;top_factors:{feature:string;impact:number}[]}> }

function getRiskTokens(level?:string){
  if(level==='HIGH')   return{color:'var(--clr-critical)',dim:'var(--critical-dim)',border:'var(--critical-border)'}
  if(level==='MEDIUM') return{color:'var(--clr-warning)', dim:'var(--warning-dim)', border:'var(--warning-border)'}
  if(level==='LOW')    return{color:'var(--clr-success)', dim:'var(--success-dim)', border:'var(--success-border)'}
  return {color:'var(--text-muted)',dim:'var(--bg-elevated)',border:'var(--border-subtle)'}
}

export default function ShiftReport({patients,results}:Props){
  const now=new Date()
  const shiftTime=now.toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})
  const shiftDate=now.toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})
  const highRisk=patients.filter(p=>results[p.id]?.risk_level==='HIGH')
  const medRisk=patients.filter(p=>results[p.id]?.risk_level==='MEDIUM')
  const lowRisk=patients.filter(p=>results[p.id]?.risk_level==='LOW')
  const unassessed=patients.filter(p=>!results[p.id])

  const handleDownload=()=>{
    let text=`BIOSIGNAL ICU SHIFT HANDOVER REPORT\nDate: ${shiftDate} | Time: ${shiftTime}\nGenerated by BioSignal ML Early Warning System\n\n=== PATIENT SUMMARY ===\nTotal Patients: ${patients.length}\nHIGH RISK: ${highRisk.length} | MEDIUM: ${medRisk.length} | LOW: ${lowRisk.length}\n\n`
    if(highRisk.length>0){text+=`=== HIGH RISK PATIENTS ===\n`;highRisk.forEach(p=>{const r=results[p.id];text+=`• ${p.name} (${p.age}y, ${p.unit}) — Risk: ${Math.round(r.risk_score*100)}%\n  Top factors: ${r.top_factors.slice(0,2).map(f=>f.feature).join(', ')}\n`});text+='\n'}
    text+=`=== ALL PATIENTS ===\n`;patients.forEach(p=>{const r=results[p.id];text+=`${p.name} | ${p.unit} | ${r?Math.round(r.risk_score*100)+'% '+r.risk_level:'NOT ASSESSED'}\n`})
    const blob=new Blob([text],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`biosignal-shift-${shiftDate}.txt`;a.click();URL.revokeObjectURL(url)
  }

  return(
    <div style={{display:'flex',flexDirection:'column',gap:'16px'}}>
      {/* Header */}
      <div style={{background:'var(--bg-card)',border:'1px solid var(--border-subtle)',borderRadius:'14px',padding:'16px 20px',display:'flex',justifyContent:'space-between',alignItems:'center'}}>
        <div>
          <p style={{fontFamily:'var(--font-display)',fontSize:'16px',fontWeight:700,color:'var(--text-primary)',marginBottom:'4px'}}>ICU Shift Handover Report</p>
          <p style={{fontSize:'11px',color:'var(--text-muted)',fontFamily:'var(--font-data)'}}>{shiftDate} · {shiftTime} · BioSignal ML System</p>
        </div>
        <button onClick={handleDownload} style={{
          display:'flex',alignItems:'center',gap:'8px',
          background:'var(--primary-dim)',border:'1px solid var(--primary-border)',
          color:'var(--clr-primary)',fontFamily:'var(--font-data)',fontSize:'11px',fontWeight:700,
          padding:'8px 16px',borderRadius:'8px',cursor:'pointer',transition:'all 0.15s',
        }}>
          <Download size={14}/> Download Report
        </button>
      </div>

      {/* Stats */}
      <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'10px'}}>
        {[
          {label:'Total Patients',count:patients.length,   color:'var(--text-primary)', dim:'var(--bg-card)',       border:'var(--border-subtle)'},
          {label:'HIGH RISK',     count:highRisk.length,   color:'var(--clr-critical)', dim:'var(--critical-dim)', border:'var(--critical-border)'},
          {label:'MEDIUM RISK',   count:medRisk.length,    color:'var(--clr-warning)',  dim:'var(--warning-dim)',  border:'var(--warning-border)'},
          {label:'LOW RISK',      count:lowRisk.length,    color:'var(--clr-success)',  dim:'var(--success-dim)',  border:'var(--success-border)'},
        ].map(s=>(
          <div key={s.label} style={{background:s.dim,border:`1px solid ${s.border}`,borderRadius:'12px',padding:'14px',textAlign:'center'}}>
            <p style={{fontSize:'10px',color:s.color,fontFamily:'var(--font-data)',letterSpacing:'1px',textTransform:'uppercase',marginBottom:'6px',opacity:0.8}}>{s.label}</p>
            <p style={{fontFamily:'var(--font-data)',fontSize:'30px',fontWeight:700,color:s.color,lineHeight:1}}>{s.count}</p>
          </div>
        ))}
      </div>

      {/* HIGH RISK detail */}
      {highRisk.length>0&&(
        <div style={{background:'var(--critical-dim)',border:'1px solid var(--critical-border)',borderRadius:'14px',padding:'16px',animation:'pulse-critical 2s ease-in-out infinite'}}>
          <p style={{fontFamily:'var(--font-display)',fontSize:'13px',fontWeight:700,color:'var(--clr-critical)',marginBottom:'12px'}}>🚨 HIGH RISK — Immediate Attention Required</p>
          <div style={{display:'flex',flexDirection:'column',gap:'8px'}}>
            {highRisk.map(p=>{
              const r=results[p.id]
              return(
                <div key={p.id} style={{background:'rgba(255,71,87,0.06)',border:'1px solid var(--critical-border)',borderRadius:'10px',padding:'12px 16px',display:'flex',justifyContent:'space-between',alignItems:'center'}}>
                  <div>
                    <p style={{fontSize:'13px',fontWeight:600,color:'var(--text-primary)',fontFamily:'var(--font-display)',marginBottom:'3px'}}>{p.name}</p>
                    <p style={{fontSize:'11px',color:'var(--text-muted)'}}>{p.age}y · {p.unit}</p>
                    <p style={{fontSize:'11px',color:'var(--clr-critical)',marginTop:'4px',fontFamily:'var(--font-data)'}}>
                      Key: {r.top_factors.slice(0,2).map(f=>f.feature.replace(/_/g,' ')).join(', ')}
                    </p>
                  </div>
                  <span style={{fontFamily:'var(--font-data)',fontSize:'24px',fontWeight:700,color:'var(--clr-critical)'}}>{Math.round(r.risk_score*100)}%</span>
                </div>
              )
            })}
          </div>
        </div>
      )}

      {/* All patients */}
      <div style={{background:'var(--bg-card)',border:'1px solid var(--border-subtle)',borderRadius:'14px',padding:'16px'}}>
        <p style={{fontSize:'10px',color:'var(--text-muted)',fontFamily:'var(--font-data)',letterSpacing:'1.5px',textTransform:'uppercase',marginBottom:'12px'}}>All Patients Status</p>
        <div style={{display:'flex',flexDirection:'column',gap:'6px'}}>
          {patients.map(p=>{
            const r=results[p.id]
            const tk=getRiskTokens(r?.risk_level)
            return(
              <div key={p.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'10px 14px',background:'var(--bg-elevated)',border:'1px solid var(--border-subtle)',borderRadius:'8px'}}>
                <div>
                  <p style={{fontSize:'13px',fontWeight:500,color:'var(--text-primary)',fontFamily:'var(--font-display)'}}>{p.name}</p>
                  <p style={{fontSize:'10px',color:'var(--text-muted)',fontFamily:'var(--font-data)',marginTop:'2px'}}>{p.age}y · {p.unit}</p>
                </div>
                {r?(
                  <div style={{display:'flex',alignItems:'center',gap:'8px'}}>
                    <span style={{fontFamily:'var(--font-data)',fontSize:'14px',fontWeight:700,color:tk.color}}>{Math.round(r.risk_score*100)}%</span>
                    <span style={{fontSize:'10px',fontWeight:600,padding:'3px 10px',borderRadius:'100px',background:tk.dim,border:`1px solid ${tk.border}`,color:tk.color,fontFamily:'var(--font-data)'}}>{r.risk_level}</span>
                  </div>
                ):(
                  <span style={{fontSize:'11px',color:'var(--text-muted)',fontFamily:'var(--font-data)',padding:'3px 10px',borderRadius:'100px',background:'var(--bg-card)',border:'1px solid var(--border-subtle)'}}>Not Assessed</span>
                )}
              </div>
            )
          })}
        </div>
      </div>

      {unassessed.length>0&&(
        <p style={{fontSize:'11px',color:'var(--clr-warning)',textAlign:'center',fontFamily:'var(--font-data)'}}>
          ⚠ {unassessed.length} patient(s) not assessed — run predictions in ML Dashboard
        </p>
      )}
    </div>
  )
}
